152 refactor
EPFL-ENAC/CCFatiguePlatform pull request #161
Opened 2022-11-10 15:56 UTC by nicdub

Refactoring according to #152
@blueur could you check make compile-win because I don't have the same env

2022-11-10 16:09 UTC, charlottegiseleweil reviewed
@nicdub sorry if I'm missing something but I can't find where you define the logic behind naming the analysis scripts (python ones) - and it doesn't seem consistent to me : something you prefix them with the data code (e.g. cyc), sometimes with the full name of the module (e.g. sncurve), could you make this consistent within this pull request ?

2022-11-11 08:00 UTC, nicdub commented
> @nicdub sorry if I'm missing something but I can't find where you define the logic behind naming the analysis scripts (python ones) - and it doesn't seem consistent to me : something you prefix them with the data code (e.g. cyc), sometimes with the full name of the module (e.g. sncurve), could you make this consistent within this pull request ?

@charlottegiseleweil not the same issue (#151), not the same PR if I understood correctly. I made a proposal in the other issue, do you approve?

2022-11-14 18:51 UTC, charlottegiseleweil approved these changes
LGTM !

2022-11-15 14:37 UTC, blueur requested changes
J'avais mal compris pour le renommage de ccfatigue vers ccfatigue_main.
Si on remonte d'autres modules ccfatigue au même niveau, ça fait sens de le renommer, mais s'il n'y a qu'un seul ccfatigue, ça ne sert à rien de le renommer.
Car la convention des projets python est d'avoir un dossier avec le nom du projet [numpy](https://github.com/numpy/numpy/tree/main/numpy), [pandas](https://github.com/pandas-dev/pandas/tree/main/pandas), [poetry](https://github.com/python-poetry/poetry/tree/master/src/poetry), ...

2022-11-16 07:14 UTC, nicdub commented
> J'avais mal compris pour le renommage de ccfatigue vers ccfatigue_main. Si on remonte d'autres modules ccfatigue au même niveau, ça fait sens de le renommer, mais s'il n'y a qu'un seul ccfatigue, ça ne sert à rien de le renommer. Car la convention des projets python est d'avoir un dossier avec le nom du projet [numpy](https://github.com/numpy/numpy/tree/main/numpy), [pandas](https://github.com/pandas-dev/pandas/tree/main/pandas), [poetry](https://github.com/python-poetry/poetry/tree/master/src/poetry), ...

@charlottegiseleweil @guilbep @sbancal @blueur ok pour tous de garder le nom ccfatigue?

2022-11-16 07:45 UTC, guilbep commented
Je laisse @blueur et @sbancal decider vu que renommer ccfatigue en api ne convenait pas.
Mais je réitère, pour moi ccfatigue c'est l'API du backend (le main.py c'est 99% du fast-api).
Et okay on initialise alembic_upgrade dedans. Mais peut-etre que c'est pas la bonne pratique.

Peut-etre qu'on devrait faire l'upgrade au moment où on run le service dans docker comme dans cet example:|
```yaml
services:
web:
    build: .
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    ...
```
https://ahmed-nafies.medium.com/fastapi-with-sqlalchemy-postgresql-and-alembic-and-of-course-docker-f2b7411ee396

Bref dans tout les cas, je trouve que ccfatigue c'est pas descriptif comme nom. Et que oui c'est pas utile d'avoir ccfatigue renommé en ccfatigue_main.

Bref vous avez mon avis. @charlottegiseleweil Est-ce que tu peux trancher ? :)

2022-11-17 15:24 UTC, blueur commented
@guilbep 
Le nom `ccfatigue` est le nom du module, on pourrait le voir comme "si on souhaite publier le module python sur pypi, quel nom il devrait avoir. Et comme c'est le module en Python du projet CCFatigue, ça fait sens pour moi de le nommer juste `ccfatigue`, après pour différencier les différents sous-module, on pourrait éventuellement le nommer `ccfatigue_backend`. 
L'API, pour moi, c'est la définition de l'interface, je ne m'attendrais pas à un serveur qui tourne en le lançant.

2022-11-18 07:57 UTC, sbancal commented
same opinion as @blueur , Python standard means keeping `ccfatigue`.
I'll roll back my changes and notify here when ready.

2022-11-18 13:21 UTC, sbancal commented
reverted to `ccfatigue`.
@guilbep @nicdub 👍🏼 👎🏼 ?!

2022-11-21 08:43 UTC, blueur approved these changes

2022-11-21 09:22 UTC, merged