163 tst data convention fix
EPFL-ENAC/CCFatiguePlatform pull request #170
Opened 2022-11-14 08:59 UTC by sbancal

Needed for #162 _FA_ with no fracture need a 2 columns.
FIX #163

2022-11-14 18:46 UTC, charlottegiseleweil requested changes
The data convention cannot be updated wihtout updating its documentation. https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/Data/TST_Data_Convention.md 

@sbancal do you plan to update all the previous datasets ?!

2022-11-15 12:12 UTC, sbancal commented
Don't understand @charlottegiseleweil 
Data convention has been updated to match the change in this PR. See `Data/TST_Data_Template.xls`.

Do you mean something else ?

2022-11-21 12:21 UTC, guilbep approved these changes

2022-11-21 13:57 UTC, sbancal commented
@charlottegiseleweil agreed in a direct message ... I force the merge

2022-11-21 13:58 UTC, merged