Feature/analysis
EPFL-ENAC/CCFatiguePlatform pull request #172
Opened 2022-11-14 14:52 UTC by blueur

2022-11-15 14:17 UTC, sbancal commented on backend/preprocessing/tst_data_lib.py
> +                    float_format="%.16g",
Running on Ubuntu 22.04 -> different values starting at least from `"%.12g"

2022-11-15 14:17 UTC, sbancal commented on backend/preprocessing/hysteresis_loops.py
> +                        float_format="%.16g",
same: `"%.12g"`

2022-11-15 14:37 UTC, sbancal commented
... see  a8d35a4b3328363bebd9f238e08826f39d15e1fc

2022-11-18 10:41 UTC, sbancal requested changes
Please check to avoid 100% empty graphs like on 
http://localhost:8080/fatigue_database/tests_dashboard?exp=5&tests=30&tests=33

thks : )

2022-11-21 09:36 UTC, sbancal approved these changes
merci : )

2022-11-21 09:36 UTC, merged

2022-12-05 14:56 UTC, vsdharun commented
@sbancal It seems the x and y-axis values are swaped. could you fix it ?



![image](https://user-images.githubusercontent.com/81630367/205667954-85aa5bfc-0e2b-4a10-ae4f-be724f5720b9.png)