Feat/fortran2py/mod2 lin log+log log
EPFL-ENAC/CCFatiguePlatform pull request #74
Opened 2022-08-24 13:01 UTC by nicdub

Complete LogLog and add LinLog based on LogLog

2022-08-25 14:39 UTC, charlottegiseleweil requested changes
Hello!
Overall, very good job translating these modules. 
However I think before merging we must improve the clarity of these scripts, in particular in terms of :

1. - variable namings and definition : must be consistent, either defined in the variable_dictionary, or explicit variable names (e.g. name the variable "slope" or "intercept", instead of "aa" and "bb"? or define it, e.g. "ycar" is not defined). "term1" and "term2" are okay, when used within the same, small function. 
2.  - organization : extract the function re-used in several methods, and put them in a side utils script.
3. - more rigorous/detailed description of the algorithm. Let's try to make the algorithm understandable just by reading the code!

These 2 methods are very simple ones, that should be easier to understand upon reading the scripts. The fortran version was a mess, this is already much better, but I think we can still improve it before merging !

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    """
Recently we found this standard syntax for Docstrings that works really well - especially for automating documentation later. Let's start using this ? Especially that ours is not super consistent between modules at the moment. 
 Can you also add the expected type of each params in the docstring?
```suggestion

 """
   Calculate stress at failure.

    Translated from : https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/CCFatigue_modules/2_S-NCurves/S-N-Curve-LinLog.for#L397

   Parameters
   ----------
   aa : float
       description of aa
   bb : float
       description of bb
   nn : float
       description of nn
   Returns
   -------
   spn : float
    stress at failure
   """

```

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    # agg_df["log10_stress_parameter"] = np.log10(agg_df.stress_parameter)
Is this line needed or not ? If yes, should not be commented out, if not, description line 101 should be adjusted

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    # can have two separate groups with same stress_ratio so we need to identify
je ne comprends pas désolée ..

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +            range(30000000, 1400000000, 100000000),
Reference of where these constants come from ?

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_loglog.py
>  def equation_ycar(
Cette fonction étant déjà utilisée dans plusieurs scripts, il faudrait la sortir et la mettre dans un aute fichier.
Si on copie-colle dans 2 scripts la même fonction, et qu'un jour on veut la changer, c'est peu efficace et on risque des erreurs. 

Je pense que dans ce cas, on peut faire un script
regression_utils.py dans lequel on mets les fonctions partagées entre ces méthodes. Puis on appelle dans ces méthodes ces fonctions là. Ce sera plus succint en terme de nombre de ligne de code! Tu peux procéder à cette réorganisation ?

Bien joué d'avoir mis ces 2 méthodes dans la même PR, ça permet d'identifier ces optimisations.

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    """
Honne^tement les nommage de variables comme ça ("aa", "bb" ça ne va pas.. C'est pas du tout descriptif..Sont-elles nommées comme ça dans la référence?) Si on a compris ce que c'était, renommmer la vairbale un peu plus explicite permettrait de mieux lire ton code..

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    """
spn par exemple, dans le variable_dictionary c'est sigma_max - pourquoi c'est spn ici ? c'est super dur à suivre.. Ca devrait être soit "sigma_max" (acronyme défini dans le variable_dictionary), soit "Stress_at_failure" (explicit variable naming

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    # Add AA and BB TODO reference for these equations
"todo" remaining

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    # Fp
where is the reference equation ? Would be useful to follow here.

2022-08-25 14:39 UTC, charlottegiseleweil commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    # NOD
Be more descriptive with what's happening?

2022-08-26 13:31 UTC, nicdub commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +
Is this suggestion part a mistake?

2022-08-26 14:14 UTC, nicdub commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +
@charlottegiseleweil This empty line was to separate external and internal libs import, should we keep it and add a comment? 
```suggestion

# Below, import of internal lib
from astm import Astm
```

2022-08-26 14:19 UTC, nicdub commented on CCFatigue_modules/2_S-NCurves/sn_curve_linlog.py
> +    https://github.com/EPFL-ENAC/CCFatiguePlatform/blob/develop/CCFatigue_modules/2_S-NCurves/S-N-Curve-LinLog.for#L314
ycar and some other variable name come from Fortran code and need clarification, how could we assign these questions to Tassos?

2022-09-12 14:24 UTC, charlottegiseleweil approved these changes
Reviewed it the first time - so fine to merge as a first version !

2022-09-13 07:30 UTC, merged